/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { PermissionAction } from "@prisma/client";
import { prisma } from "../../../lib/prisma";
import { bad, cleanString, dateValue, numberValue, requireModule, writeAudit } from "../../../lib/apiUtils";
const MODULE="CRM"; const db=prisma as any;
export async function GET(){const auth=await requireModule(MODULE,PermissionAction.VIEW); if("response" in auth)return auth.response; const organizationId=auth.user.organizationId; const [leads,opportunities,customers,projects]=await Promise.all([db.crmLead.findMany({where:{organizationId},include:{customer:true,createdBy:true,_count:{select:{opportunities:true}}},orderBy:{updatedAt:"desc"},take:100}),db.crmOpportunity.findMany({where:{organizationId},include:{lead:true,customer:true,project:true},orderBy:{updatedAt:"desc"},take:100}),prisma.customer.findMany({where:{organizationId},select:{id:true,code:true,name:true}}),prisma.project.findMany({where:{organizationId},select:{id:true,code:true,name:true}})]); return NextResponse.json({ok:true,leads,opportunities,customers,projects});}
export async function POST(request:Request){const auth=await requireModule(MODULE,PermissionAction.CREATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(body.kind==="opportunity"){if(!body.name)return bad("Thiếu tên cơ hội."); const count=await db.crmOpportunity.count({where:{organizationId:auth.user.organizationId}}); const opportunity=await db.crmOpportunity.create({data:{organizationId:auth.user.organizationId,leadId:body.leadId||null,customerId:body.customerId||null,projectId:body.projectId||null,code:cleanString(body.code)||`OPP-${String(count+1).padStart(5,"0")}`,name:cleanString(body.name),stage:cleanString(body.stage)||"QUALIFYING",probability:numberValue(body.probability,10),estimatedValueVnd:numberValue(body.estimatedValueVnd),expectedCloseDate:dateValue(body.expectedCloseDate),metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo cơ hội CRM ${opportunity.code}.`,"crmOpportunity",opportunity.id); return NextResponse.json({ok:true,opportunity},{status:201});}
 if(!body.companyName)return bad("Thiếu tên công ty lead."); const count=await db.crmLead.count({where:{organizationId:auth.user.organizationId}}); const lead=await db.crmLead.create({data:{organizationId:auth.user.organizationId,customerId:body.customerId||null,createdById:auth.user.id,code:cleanString(body.code)||`LEAD-${String(count+1).padStart(5,"0")}`,companyName:cleanString(body.companyName),contactName:cleanString(body.contactName)||null,contactEmail:cleanString(body.contactEmail)||null,country:cleanString(body.country)||null,source:cleanString(body.source)||"Website",stage:cleanString(body.stage)||"NEW",estimatedValueVnd:numberValue(body.estimatedValueVnd),nextActionAt:dateValue(body.nextActionAt),notes:cleanString(body.notes)||null,metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo lead CRM ${lead.code}.`,"crmLead",lead.id); return NextResponse.json({ok:true,lead},{status:201});}
