/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { PermissionAction } from "@prisma/client";
import { prisma } from "../../../lib/prisma";
import { bad, cleanString, dateValue, numberValue, requireModule, writeAudit } from "../../../lib/apiUtils";
const MODULE="CONTRACTS"; const db=prisma as any;
export async function GET(){const auth=await requireModule(MODULE,PermissionAction.VIEW); if("response" in auth)return auth.response; const organizationId=auth.user.organizationId; const [contracts,projects,customers]=await Promise.all([db.contract.findMany({where:{organizationId},include:{project:true,customer:true,department:true,createdBy:true},orderBy:{createdAt:"desc"},take:100}),prisma.project.findMany({where:{organizationId},select:{id:true,code:true,name:true}}),prisma.customer.findMany({where:{organizationId},select:{id:true,code:true,name:true}})]); return NextResponse.json({ok:true,contracts,projects,customers});}
export async function POST(request:Request){const auth=await requireModule(MODULE,PermissionAction.CREATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(!body?.title)return bad("Thiếu tên hợp đồng."); const count=await db.contract.count({where:{organizationId:auth.user.organizationId}}); const code=cleanString(body.code)||`HD-${String(count+1).padStart(5,"0")}`; const contract=await db.contract.create({data:{organizationId:auth.user.organizationId,projectId:body.projectId||null,customerId:body.customerId||null,departmentId:auth.user.departmentId,createdById:auth.user.id,code,contractNo:cleanString(body.contractNo)||null,title:cleanString(body.title),type:cleanString(body.type)||"EPC",status:cleanString(body.status)||"DRAFT",currency:cleanString(body.currency)||"VND",valueVnd:numberValue(body.valueVnd),vatRate:numberValue(body.vatRate),retentionRate:numberValue(body.retentionRate),signedDate:dateValue(body.signedDate),startDate:dateValue(body.startDate),endDate:dateValue(body.endDate),metadata:body.metadata||body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo hợp đồng ${contract.code}.`,"contract",contract.id); return NextResponse.json({ok:true,contract},{status:201});}
export async function PATCH(request:Request){const auth=await requireModule(MODULE,PermissionAction.UPDATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(!body?.id)return bad("Thiếu ID hợp đồng."); const contract=await db.contract.update({where:{id:body.id},data:{title:body.title,contractNo:body.contractNo||null,status:body.status,type:body.type,valueVnd:body.valueVnd!==undefined?numberValue(body.valueVnd):undefined,vatRate:body.vatRate!==undefined?numberValue(body.vatRate):undefined,retentionRate:body.retentionRate!==undefined?numberValue(body.retentionRate):undefined,signedDate:body.signedDate!==undefined?dateValue(body.signedDate):undefined,startDate:body.startDate!==undefined?dateValue(body.startDate):undefined,endDate:body.endDate!==undefined?dateValue(body.endDate):undefined}}); await writeAudit(auth.user,MODULE,PermissionAction.UPDATE,`Cập nhật hợp đồng ${contract.code}.`,"contract",contract.id); return NextResponse.json({ok:true,contract});}
export async function DELETE(request:Request){const auth=await requireModule(MODULE,PermissionAction.DELETE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(!body?.id)return bad("Thiếu ID hợp đồng."); await db.contract.delete({where:{id:body.id}}); await writeAudit(auth.user,MODULE,PermissionAction.DELETE,"Xóa hợp đồng.","contract",body.id); return NextResponse.json({ok:true});}
