/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { PermissionAction } from "@prisma/client";
import { prisma } from "../../../lib/prisma";
import { bad, cleanString, numberValue, requireModule, writeAudit } from "../../../lib/apiUtils";
const MODULE="GIS_MAP"; const db=prisma as any;
export async function GET(){const auth=await requireModule(MODULE,PermissionAction.VIEW); if("response" in auth)return auth.response; const organizationId=auth.user.organizationId; const [layers,features,projects]=await Promise.all([db.gisLayer.findMany({where:{organizationId},include:{_count:{select:{features:true}}},orderBy:{name:"asc"}}),db.gisFeature.findMany({where:{organizationId},include:{layer:true,project:true},take:500}),prisma.project.findMany({where:{organizationId},select:{id:true,code:true,name:true,lat:true,lng:true,province:true,status:true,progress:true}})]); return NextResponse.json({ok:true,layers,features,projects,googleMaps:{configured:Boolean(process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY)}});}
export async function POST(request:Request){const auth=await requireModule(MODULE,PermissionAction.CREATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(body.kind==="layer"){if(!body.name)return bad("Thiếu tên layer."); const count=await db.gisLayer.count({where:{organizationId:auth.user.organizationId}}); const layer=await db.gisLayer.create({data:{organizationId:auth.user.organizationId,code:cleanString(body.code)||`GIS-${String(count+1).padStart(3,"0")}`,name:cleanString(body.name),layerType:cleanString(body.layerType)||"PROJECT",visible:body.visible!==false,style:body.style||null,metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo GIS layer ${layer.code}.`,"gisLayer",layer.id); return NextResponse.json({ok:true,layer},{status:201});}
 if(!body.layerId||!body.name)return bad("Thiếu layer hoặc tên điểm GIS."); const count=await db.gisFeature.count({where:{organizationId:auth.user.organizationId}}); const geometry=body.geometry||{type:"Point",coordinates:[numberValue(body.lng),numberValue(body.lat)]}; const feature=await db.gisFeature.create({data:{organizationId:auth.user.organizationId,layerId:body.layerId,projectId:body.projectId||null,code:cleanString(body.code)||`GEOF-${String(count+1).padStart(5,"0")}`,name:cleanString(body.name),geometry,properties:body.properties||body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo GIS feature ${feature.code}.`,"gisFeature",feature.id); return NextResponse.json({ok:true,feature},{status:201});}
