/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { PermissionAction } from "@prisma/client";
import { prisma } from "../../../lib/prisma";
import { bad, cleanString, requireModule, writeAudit, moduleCode } from "../../../lib/apiUtils";
const MODULE="ERP"; const db=prisma as any;
export async function GET(){const auth=await requireModule(MODULE,PermissionAction.VIEW); if("response" in auth)return auth.response; const organizationId=auth.user.organizationId; const [processes,approvals,users]=await Promise.all([db.erpProcess.findMany({where:{organizationId},include:{_count:{select:{approvals:true}}},orderBy:{name:"asc"}}),db.erpApproval.findMany({where:{organizationId},include:{process:true,createdBy:true,assignee:true},orderBy:{createdAt:"desc"},take:100}),prisma.user.findMany({where:{organizationId},select:{id:true,name:true,email:true}})]); return NextResponse.json({ok:true,processes,approvals,users});}
export async function POST(request:Request){const auth=await requireModule(MODULE,PermissionAction.CREATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(body.kind==="process"){if(!body.name)return bad("Thiếu tên quy trình."); const count=await db.erpProcess.count({where:{organizationId:auth.user.organizationId}}); const process=await db.erpProcess.create({data:{organizationId:auth.user.organizationId,code:cleanString(body.code)||`WF-${String(count+1).padStart(4,"0")}`,name:cleanString(body.name),module:moduleCode(cleanString(body.module)||"ERP"),steps:body.steps||[{step:1,name:"Người lập"},{step:2,name:"Trưởng bộ phận"},{step:3,name:"Ban lãnh đạo"}],isActive:body.isActive!==false}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo quy trình ERP ${process.code}.`,"erpProcess",process.id); return NextResponse.json({ok:true,process},{status:201});}
 if(!body.title)return bad("Thiếu tiêu đề phê duyệt."); const count=await db.erpApproval.count({where:{organizationId:auth.user.organizationId}}); const approval=await db.erpApproval.create({data:{organizationId:auth.user.organizationId,processId:body.processId||null,createdById:auth.user.id,assigneeId:body.assigneeId||null,code:cleanString(body.code)||`APR-${String(count+1).padStart(5,"0")}`,title:cleanString(body.title),module:moduleCode(cleanString(body.module)||"ERP"),entity:cleanString(body.entity)||null,entityId:cleanString(body.entityId)||null,status:cleanString(body.status)||"PENDING",payload:body.payload||body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo yêu cầu phê duyệt ${approval.code}.`,"erpApproval",approval.id); return NextResponse.json({ok:true,approval},{status:201});}
export async function PATCH(request:Request){const auth=await requireModule(MODULE,PermissionAction.APPROVE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(!body?.id)return bad("Thiếu ID phê duyệt."); const approval=await db.erpApproval.update({where:{id:body.id},data:{status:cleanString(body.status)||"APPROVED",assigneeId:auth.user.id,approvedAt:body.status==="APPROVED"?new Date():null}}); await writeAudit(auth.user,MODULE,PermissionAction.APPROVE,`Xử lý phê duyệt ${approval.code}.`,"erpApproval",approval.id); return NextResponse.json({ok:true,approval});}
