/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { PermissionAction } from "@prisma/client";
import { prisma } from "../../../lib/prisma";
import { bad, cleanString, dateValue, numberValue, requireModule, writeAudit } from "../../../lib/apiUtils";
const MODULE="DEBT"; const db=prisma as any;
export async function GET(){const auth=await requireModule(MODULE,PermissionAction.VIEW); if("response" in auth)return auth.response; const organizationId=auth.user.organizationId; const [debts,contracts,projects]=await Promise.all([db.debtLedger.findMany({where:{organizationId},include:{project:true,contract:true,paymentRequest:true},orderBy:{dueDate:"asc"},take:200}),db.contract.findMany({where:{organizationId},select:{id:true,code:true,title:true}}),prisma.project.findMany({where:{organizationId},select:{id:true,code:true,name:true}})]); const totals={receivable:0,payable:0,overdue:0}; for(const d of debts){if(d.type==="PAYABLE")totals.payable+=d.amountVnd-d.paidVnd; else totals.receivable+=d.amountVnd-d.paidVnd; if(d.dueDate&&new Date(d.dueDate)<new Date()&&d.status!=="PAID")totals.overdue+=d.amountVnd-d.paidVnd;} return NextResponse.json({ok:true,debts,contracts,projects,totals});}
export async function POST(request:Request){const auth=await requireModule(MODULE,PermissionAction.CREATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(!body?.partnerName)return bad("Thiếu đối tác/công nợ."); const count=await db.debtLedger.count({where:{organizationId:auth.user.organizationId}}); const code=cleanString(body.code)||`CN-${String(count+1).padStart(5,"0")}`; const debt=await db.debtLedger.create({data:{organizationId:auth.user.organizationId,projectId:body.projectId||null,contractId:body.contractId||null,paymentRequestId:body.paymentRequestId||null,code,partnerName:cleanString(body.partnerName),type:cleanString(body.type)||"RECEIVABLE",amountVnd:numberValue(body.amountVnd),paidVnd:numberValue(body.paidVnd),dueDate:dateValue(body.dueDate),status:cleanString(body.status)||"OPEN",notes:cleanString(body.notes)||null,metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo công nợ ${debt.code}.`,"debtLedger",debt.id); return NextResponse.json({ok:true,debt},{status:201});}
export async function PATCH(request:Request){const auth=await requireModule(MODULE,PermissionAction.UPDATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(!body?.id)return bad("Thiếu ID công nợ."); const debt=await db.debtLedger.update({where:{id:body.id},data:{partnerName:body.partnerName,type:body.type,amountVnd:body.amountVnd!==undefined?numberValue(body.amountVnd):undefined,paidVnd:body.paidVnd!==undefined?numberValue(body.paidVnd):undefined,dueDate:body.dueDate!==undefined?dateValue(body.dueDate):undefined,status:body.status,notes:body.notes}}); await writeAudit(auth.user,MODULE,PermissionAction.UPDATE,`Cập nhật công nợ ${debt.code}.`,"debtLedger",debt.id); return NextResponse.json({ok:true,debt});}
