/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { PermissionAction } from "@prisma/client";
import { prisma } from "../../../lib/prisma";
import { bad, cleanString, dateValue, numberValue, requireModule, writeAudit } from "../../../lib/apiUtils";
const MODULE="FINANCE"; const db=prisma as any;
export async function GET(){const auth=await requireModule(MODULE,PermissionAction.VIEW); if("response" in auth)return auth.response; const organizationId=auth.user.organizationId; const [accounts,entries,lines]=await Promise.all([db.financeAccount.findMany({where:{organizationId},orderBy:{code:"asc"},take:300}),db.journalEntry.findMany({where:{organizationId},include:{createdBy:true,_count:{select:{lines:true}}},orderBy:{postingDate:"desc"},take:100}),db.journalLine.findMany({where:{organizationId},include:{entry:true,debitAccount:true,creditAccount:true},take:200})]); return NextResponse.json({ok:true,accounts,entries,lines});}
export async function POST(request:Request){const auth=await requireModule(MODULE,PermissionAction.CREATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(body.kind==="account"){if(!body.code||!body.name)return bad("Thiếu mã hoặc tên tài khoản."); const account=await db.financeAccount.upsert({where:{organizationId_code:{organizationId:auth.user.organizationId,code:cleanString(body.code)}},update:{name:cleanString(body.name),type:cleanString(body.type)||"ASSET",parentCode:cleanString(body.parentCode)||null,isActive:body.isActive!==false,metadata:body},create:{organizationId:auth.user.organizationId,code:cleanString(body.code),name:cleanString(body.name),type:cleanString(body.type)||"ASSET",parentCode:cleanString(body.parentCode)||null,isActive:body.isActive!==false,metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo/cập nhật tài khoản kế toán ${account.code}.`,"financeAccount",account.id); return NextResponse.json({ok:true,account},{status:201});}
 if(!body.description)return bad("Thiếu diễn giải bút toán."); const count=await db.journalEntry.count({where:{organizationId:auth.user.organizationId}}); const entry=await db.journalEntry.create({data:{organizationId:auth.user.organizationId,createdById:auth.user.id,code:cleanString(body.code)||`BT-${String(count+1).padStart(5,"0")}`,postingDate:dateValue(body.postingDate)||new Date(),description:cleanString(body.description),sourceModule:cleanString(body.sourceModule)||null,status:cleanString(body.status)||"DRAFT",metadata:body}}); for(const line of body.lines||[]){await db.journalLine.create({data:{organizationId:auth.user.organizationId,entryId:entry.id,debitAccountId:line.debitAccountId||null,creditAccountId:line.creditAccountId||null,amountVnd:numberValue(line.amountVnd),description:cleanString(line.description)||null,projectCode:cleanString(line.projectCode)||null,metadata:line}})} await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo bút toán ${entry.code}.`,"journalEntry",entry.id); return NextResponse.json({ok:true,entry},{status:201});}
