/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { PermissionAction } from "@prisma/client";
import { prisma } from "../../../lib/prisma";
import { bad, cleanString, dateValue, numberValue, requireModule, writeAudit } from "../../../lib/apiUtils";
const MODULE="PLANNING"; const db=prisma as any;
export async function GET(){const auth=await requireModule(MODULE,PermissionAction.VIEW); if("response" in auth)return auth.response; const organizationId=auth.user.organizationId; const [plans,tasks,reports,projects]=await Promise.all([db.constructionPlan.findMany({where:{organizationId},include:{project:true,_count:{select:{tasks:true}}},orderBy:{updatedAt:"desc"},take:100}),db.planTask.findMany({where:{organizationId},include:{project:true,plan:true},orderBy:{startDate:"asc"},take:200}),db.dailyReport.findMany({where:{organizationId},include:{project:true,createdBy:true},orderBy:{reportDate:"desc"},take:50}),prisma.project.findMany({where:{organizationId},select:{id:true,code:true,name:true,progress:true}})]); return NextResponse.json({ok:true,plans,tasks,reports,projects});}
export async function POST(request:Request){const auth=await requireModule(MODULE,PermissionAction.CREATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; const kind=body?.kind||"plan"; if(kind==="report"){if(!body.projectId||!body.workDone)return bad("Thiếu dự án hoặc nội dung nhật ký."); const report=await db.dailyReport.create({data:{organizationId:auth.user.organizationId,projectId:body.projectId,createdById:auth.user.id,reportDate:dateValue(body.reportDate)||new Date(),weather:cleanString(body.weather)||null,manpowerCount:numberValue(body.manpowerCount),equipmentCount:numberValue(body.equipmentCount),workDone:cleanString(body.workDone),issues:cleanString(body.issues)||null,safetyNotes:cleanString(body.safetyNotes)||null,progress:numberValue(body.progress),metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,"Tạo nhật ký công trường.","dailyReport",report.id); return NextResponse.json({ok:true,report},{status:201});}
 if(kind==="task"){if(!body.planId||!body.projectId||!body.name)return bad("Thiếu kế hoạch/dự án/tên công việc."); const count=await db.planTask.count({where:{organizationId:auth.user.organizationId}}); const task=await db.planTask.create({data:{organizationId:auth.user.organizationId,projectId:body.projectId,planId:body.planId,parentId:body.parentId||null,code:cleanString(body.code)||`WBS-${String(count+1).padStart(5,"0")}`,name:cleanString(body.name),wbs:cleanString(body.wbs)||null,startDate:dateValue(body.startDate),endDate:dateValue(body.endDate),progress:numberValue(body.progress),status:cleanString(body.status)||"TODO",critical:Boolean(body.critical),dependencies:body.dependencies||null,metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,"Tạo WBS task.","planTask",task.id); return NextResponse.json({ok:true,task},{status:201});}
 if(!body?.projectId||!body?.name)return bad("Thiếu dự án hoặc tên kế hoạch."); const count=await db.constructionPlan.count({where:{organizationId:auth.user.organizationId}}); const plan=await db.constructionPlan.create({data:{organizationId:auth.user.organizationId,projectId:body.projectId,departmentId:auth.user.departmentId,code:cleanString(body.code)||`KH-${String(count+1).padStart(5,"0")}`,name:cleanString(body.name),status:cleanString(body.status)||"PLANNING",baselineStart:dateValue(body.baselineStart),baselineFinish:dateValue(body.baselineFinish),forecastFinish:dateValue(body.forecastFinish),progress:numberValue(body.progress),metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo kế hoạch thi công ${plan.code}.`,"constructionPlan",plan.id); return NextResponse.json({ok:true,plan},{status:201});}
