/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { PermissionAction } from "@prisma/client";
import { prisma } from "../../../lib/prisma";
import { bad, cleanString, dateValue, numberValue, requireModule, writeAudit } from "../../../lib/apiUtils";
const MODULE="PAYMENTS"; const db=prisma as any;
export async function GET(){const auth=await requireModule(MODULE,PermissionAction.VIEW); if("response" in auth)return auth.response; const organizationId=auth.user.organizationId; const [payments,contracts,projects]=await Promise.all([db.paymentRequest.findMany({where:{organizationId},include:{project:true,contract:true,createdBy:true,approvedBy:true},orderBy:{createdAt:"desc"},take:100}),db.contract.findMany({where:{organizationId},select:{id:true,code:true,title:true,valueVnd:true}}),prisma.project.findMany({where:{organizationId},select:{id:true,code:true,name:true}})]); return NextResponse.json({ok:true,payments,contracts,projects});}
export async function POST(request:Request){const auth=await requireModule(MODULE,PermissionAction.CREATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(!body?.title)return bad("Thiếu tiêu đề đề nghị thanh toán."); const count=await db.paymentRequest.count({where:{organizationId:auth.user.organizationId}}); const code=cleanString(body.code)||`TT-${String(count+1).padStart(5,"0")}`; const payment=await db.paymentRequest.create({data:{organizationId:auth.user.organizationId,projectId:body.projectId||null,contractId:body.contractId||null,createdById:auth.user.id,code,title:cleanString(body.title),phase:cleanString(body.phase)||null,amountVnd:numberValue(body.amountVnd),dueDate:dateValue(body.dueDate),paidDate:dateValue(body.paidDate),status:cleanString(body.status)||"REQUESTED",invoiceNo:cleanString(body.invoiceNo)||null,metadata:body}}); await writeAudit(auth.user,MODULE,PermissionAction.CREATE,`Tạo đề nghị thanh toán ${payment.code}.`,"paymentRequest",payment.id); return NextResponse.json({ok:true,payment},{status:201});}
export async function PATCH(request:Request){const auth=await requireModule(MODULE,PermissionAction.UPDATE); if("response" in auth)return auth.response; const body=await request.json().catch(()=>null) as any; if(!body?.id)return bad("Thiếu ID thanh toán."); const data:any={}; for(const key of ["title","phase","status","invoiceNo"]) if(body[key]!==undefined)data[key]=body[key]||null; if(body.amountVnd!==undefined)data.amountVnd=numberValue(body.amountVnd); if(body.dueDate!==undefined)data.dueDate=dateValue(body.dueDate); if(body.paidDate!==undefined)data.paidDate=dateValue(body.paidDate); if(body.status==="APPROVED")data.approvedById=auth.user.id; const payment=await db.paymentRequest.update({where:{id:body.id},data}); await writeAudit(auth.user,MODULE,PermissionAction.UPDATE,`Cập nhật thanh toán ${payment.code}.`,"paymentRequest",payment.id); return NextResponse.json({ok:true,payment});}
